# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-8uCNQYCo42YSsALEO8lm5xfYAUXoH_
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

model = YOLO('yolov8n.pt')  # nano version, fast and lightweight

"""# ***Image***

Upload an image
"""

from google.colab import files
uploaded = files.upload()

"""Read Image"""

image_path = list(uploaded.keys())[0]
img = cv2.imread(image_path)

results = model(img)


cv2_imshow(results[0].plot())

"""# ***Video***"""

video_path = "/content/From KlickPin CF محمد ریاض صدیقی 🇮🇳 adlı kullanıcının Cute panosundaki Pin 2025 _ Dini çalışmalar Islam Doğal afet.mp4"
results_video = model.predict(source=video_path, stream=True, show=False)

"""For mp4 Videos"""

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
output_video_path = 'output_video_with_detections.mp4'

first_result = next(results_video)
frame = first_result.plot()
height, width, _ = frame.shape
out = cv2.VideoWriter(output_video_path, fourcc, 20.0, (width, height))

results_video = model.predict(source=video_path, stream=True, show=False )

print("Processing video frames...")
for r in results_video:
    im_array = r.plot()
    out.write(im_array)

out.release()
print(f"Processed video saved to {output_video_path}")

results_video = model.predict(source=video_path, stream=True, show=False, verbose=False)

first_result = None
try:

    first_result = next(results_video)
except StopIteration:
    print("No frames found in the video stream. The video might be empty or corrupted.")


if first_result is not None:
    frame = first_result.plot()
    height, width, _ = frame.shape


    out = cv2.VideoWriter(output_video_path, fourcc, 20.0, (width, height))

    out.write(frame)

    print("Processing video frames...")

    for r in results_video:
        im_array = r.plot()
        out.write(im_array)

    out.release()
    print(f"Processed video saved to {output_video_path}")
else:
    print("Skipping video writing as no frames were available to process.")

from IPython.display import Video

# Display the processed video with detections
Video('output_video_with_detections.mp4', embed=True)